// <auto-generated />
using System;
using CarPoolSystem.Services.OfferRideAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarPoolSystem.Services.OfferRideAPI.Migrations
{
    [DbContext(typeof(MyContext))]
    partial class MyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarPoolSystem.Services.OfferRideAPI.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Car_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Car_Name = "Honda"
                        },
                        new
                        {
                            Id = 2,
                            Car_Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Car_Name = "Tesla Model"
                        },
                        new
                        {
                            Id = 4,
                            Car_Name = "Toyota"
                        },
                        new
                        {
                            Id = 5,
                            Car_Name = "Nissan"
                        },
                        new
                        {
                            Id = 6,
                            Car_Name = "Jeep Grand"
                        },
                        new
                        {
                            Id = 7,
                            Car_Name = "Hyundai"
                        },
                        new
                        {
                            Id = 8,
                            Car_Name = "Subaru"
                        },
                        new
                        {
                            Id = 9,
                            Car_Name = "Crislar Pacifica"
                        },
                        new
                        {
                            Id = 10,
                            Car_Name = "Mazda"
                        });
                });

            modelBuilder.Entity("CarPoolSystem.Services.OfferRideAPI.Model.Offer", b =>
                {
                    b.Property<int>("Offer_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Offer_Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Phone_no")
                        .HasColumnType("bigint");

                    b.Property<int>("Seat_Available")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Offer_Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Offer");
                });

            modelBuilder.Entity("CarPoolSystem.Services.OfferRideAPI.Model.Offer", b =>
                {
                    b.HasOne("CarPoolSystem.Services.OfferRideAPI.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
